"""
Django settings for employee_system project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ========== 环境区分（核心：开发/生产环境自动切换） ==========
# 开发环境：本地运行 | 生产环境：部署后运行
# 可通过环境变量控制：export DJANGO_ENV=production
ENV = os.environ.get('DJANGO_ENV', 'development')
IS_PRODUCTION = ENV == 'production'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境建议通过环境变量设置：export DJANGO_SECRET_KEY="你的安全密钥"
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', "django-insecure-^-lid8yla4_&-!%-jvlnsz))v477pmv0f+q=3heh&-8+gtu=)p")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

# 允许访问的域名（生产环境必须配置，开发环境通配）
if IS_PRODUCTION:
    ALLOWED_HOSTS = ['你的域名.com', 'www.你的域名.com', '127.0.0.1', 'localhost']
else:
    ALLOWED_HOSTS = ['*']  # 开发环境允许所有域名


# Application definition
INSTALLED_APPS = [
    # 第三方美化后台（建议放在最前面）
    'jazzmin',

    # Django 默认自带的应用（必须保留）
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 本地应用
    'tasks',
    'users',

    # 第三方库（DRF/JWT/CORS）
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

# Jazzmin 后台美化配置
JAZZMIN_SETTINGS = {
    # 基础标题配置
    "site_title": "任务管理系统后台",
    "site_header": "任务管理系统",
    "site_brand": "任务管理",
    # Logo（可选，需放在static/images/下）
    # "site_logo": "images/logo.png",
    # 登录页面背景图（可选）
    # "login_bg_image": "images/bg.jpg",
    # 自定义CSS（可选）
    # "custom_css": "css/custom.css",

    # 看板数据配置（关联后台统计接口）
    "dashboard": {
        "default": {
            "widgets": [
                {
                    "type": "html",
                    "content": """
                    <div class="row">
                        <div class="col-md-3">
                            <div class="info-box bg-info">
                                <span class="info-box-icon"><i class="fas fa-users"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">总用户数</span>
                                    <span class="info-box-number" id="total_users">加载中...</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="info-box bg-success">
                                <span class="info-box-icon"><i class="fas fa-user-plus"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">今日新增</span>
                                    <span class="info-box-number" id="today_new_users">加载中...</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="info-box bg-warning">
                                <span class="info-box-icon"><i class="fas fa-tasks"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">任务总数</span>
                                    <span class="info-box-number" id="total_tasks">加载中...</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="info-box bg-danger">
                                <span class="info-box-icon"><i class="fas fa-clock"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">待处理任务</span>
                                    <span class="info-box-number" id="pending_tasks">加载中...</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script>
                    // 拉取后台统计数据（避免直接查库）
                    fetch('/admin/dashboard/stats/')
                        .then(response => {
                            if (!response.ok) throw new Error('数据加载失败');
                            return response.json();
                        })
                        .then(data => {
                            document.getElementById('total_users').textContent = data.total_users || 0;
                            document.getElementById('today_new_users').textContent = data.today_new_users || 0;
                            document.getElementById('total_tasks').textContent = data.total_tasks || 0;
                            document.getElementById('pending_tasks').textContent = data.pending_tasks || 0;
                        })
                        .catch(err => {
                            console.error('看板数据加载失败：', err);
                            ['total_users', 'today_new_users', 'total_tasks', 'pending_tasks'].forEach(id => {
                                document.getElementById(id).textContent = '加载失败';
                            });
                        });
                    </script>
                    """
                }
            ]
        }
    }
}

# Jazzmin UI 样式配置
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# REST framework 核心配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'users.throttling.UserApiThrottle',
    #     'users.throttling.AnonApiThrottle',
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'user': '100/day',
    #     'anon': '50/day',
    # },
    # ✅ 新增：API文档配置（便于调试）
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}

# SIMPLE_JWT 完整配置
SIMPLE_JWT = {
    # 基础有效期
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),

    # 加密与标识配置
    'ALGORITHM': 'HS256',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # 安全扩展配置
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    # ✅ 新增：token刷新有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# 中间件配置（注意顺序：corsheaders必须在CommonMiddleware之前）
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS中间件（关键）
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ========== 跨域配置（区分开发/生产） ==========
if IS_PRODUCTION:
    # 生产环境：仅允许指定前端域名
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "https://你的前端域名.com",
        "http://localhost:8080",  # 本地调试前端
    ]
else:
    # 开发环境：允许所有域名（方便调试）
    CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True  # 允许携带token/cookie
# ✅ 新增：允许的请求头（避免前端请求被拦截）
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = "employee_system.urls"

# 模板配置
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # 后台统计上下文（如需启用请确保该文件存在）
                # "employee_system.admin_context.admin_dashboard_context",
            ],
        },
    },
]

WSGI_APPLICATION = "employee_system.wsgi.application"

# ========== 数据库配置（区分开发/生产） ==========
# 生产环境建议通过环境变量配置数据库密码
DB_PASSWORD = os.environ.get('DB_PASSWORD', 'lingling1006')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'task_manager',
        'USER': 'root',
        'PASSWORD': DB_PASSWORD,
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            # ✅ 新增：防止MySQL连接超时
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}
# 自定义用户模型设置
AUTH_USER_MODEL = 'users.User'

# ========== 日志配置（完善错误记录） ==========
# 确保日志目录存在（避免启动报错）
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if not IS_PRODUCTION else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # 滚动日志（避免文件过大）
            'filename': LOG_DIR / 'employee_system.log',
            'maxBytes': 1024 * 1024 * 50,  # 50MB
            'backupCount': 5,  # 保留5个备份
            'formatter': 'verbose',
            'encoding': 'utf-8'
        },
        # ✅ 新增：错误日志单独记录
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'error.log',
            'maxBytes': 1024 * 1024 * 50,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'tasks': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # ✅ 新增：记录SQL执行（开发环境调试用）
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if not IS_PRODUCTION else 'INFO',
            'propagate': False,
        },
    },
}

# ========== 静态/媒体文件配置 ==========
STATIC_URL = '/static/'
# 开发环境：静态文件目录
STATICFILES_DIRS = [BASE_DIR / 'static']
# 生产环境：静态文件收集目录（部署时执行 python manage.py collectstatic）
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 媒体文件配置（文件上传）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ========== Redis缓存配置（可选） ==========
# 如需启用Redis，请先安装：pip install django-redis
try:
    import django_redis
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                # 连接超时配置
                'CONNECT_TIMEOUT': 5,
                'PICKLE_VERSION': -1,
            }
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
except ImportError:
    # 未安装Redis则使用默认缓存（不影响核心功能）
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# 国际化配置（改为中文+上海时区）
LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"