# Generated by Django 4.2.29 on 2026-03-25 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, verbose_name="登录用户名"),
                ),
                ("ip_address", models.CharField(max_length=50, verbose_name="IP地址")),
                (
                    "login_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登录时间"
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(default=False, verbose_name="是否登录成功"),
                ),
                (
                    "error_msg",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="错误信息"
                    ),
                ),
            ],
            options={
                "verbose_name": "登录记录",
                "verbose_name_plural": "登录记录",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="任务名称")),
                ("manager", models.CharField(max_length=50, verbose_name="负责人")),
                ("create_time", models.DateField(verbose_name="创建时间")),
                ("deadline", models.DateField(verbose_name="截止时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待完成"),
                            ("completed", "已完成"),
                            ("overdue", "已逾期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("desc", models.TextField(blank=True, verbose_name="任务描述")),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "db_table": "tasks",
                "ordering": ["-create_time"],
            },
        ),
    ]
